### ISSUE TITLE
Adding a subquery aliasing example to the doc

### ISSUE THREAD

**Issue by cjauvin** [jkk/honeysql#10]
First let me thank you for your very nice library. I am in the process of learning Clojure by porting parts of a Python webapp backend I wrote, and I've been drawn to it with arguments like "declarative data manipulation over ORM", "plain data structures over objects", which are exactly in line with how I've been thinking for a while, without being able to really articulate it. In fact Honey SQL seems similar in spirit (although quite superior I think) to my own little module I use to wrap SQL with plain Python data structures (instead of using a full ORM, or even something lower level like SQLAlchemy Core):

https://github.com/cjauvin/little_pger

Anyway, I began using Honey SQL today and one thing I struggled with is how to alias a subquery like this one (although I agree it's not a very good example), which is mandatory for Postgres:

``` sql
select count(*) from (select * from client) as foo
```

By fiddling around I've been able to find that this works:

``` clojure
(-> (select :%count.*)
    (from [(-> (select :*)
                (from :client)) "foo"])
    (sql/format))
```

but I thought it would be useful to have an example in the doc.

**Comment by bcambel** [comment]
+1 , 2 years and still valuable :)

**Comment by jrdoane** [comment]
For what it's worth, I'm going to play devil's advocate here. They (sub-queries and aliasing,) don't really behave any differently separate than when you put them together. It just writes strangely which is why when I do this, I'm working with the map directly instead of using helper functions because it's not unrealistic that you'll want to re-use or alter certain stanzas.

I see the example above and would be tempted to write it without the helpers:
```clj
(sql/format {:select [:%count.*] :from [[{:select [:*] :from [:client]} :foo]]})
```

Personally, the only thing that looks weird is the sub-query itself, so you could just pull it apart and it looks normal again.

```clj
(def sub-query {:select [:*] :from [:client]})
(def full-query {:select [:%count.*] :from [[sub-query :foo]]})
(sql/format full-query)
```

For what it is worth, there are sub-query examples and aliasing examples. Is it really not obvious that the two can be put together and still work?

**Comment by seancorfield** [comment]
@jrdoane I'm looking over the README and don't see examples of either. Where are you seeing examples of these? (figuring out where best to add more examples)

**Comment by seancorfield** [comment]
I've just added an example of aliasing to the README. There are two examples of nested selects but neither lend themselves to adding aliasing. PRs welcome to improve the README in this area!

**Comment by seancorfield** [comment]
Closing this in the absence of a PR or further feedback. FWIW, I agree with @jrdoane that these things don't behave any differently together than they do separately: `(-> ... (from [sql-expression the-alias]) ...)` so I'm not sure what could be clearer in the README (but I'll certainly accept PRs for improvements -- just bear in mind that the README can't include _every_ combination of features in the library because that would be huge!).
