### ISSUE TITLE
Any plans to add support for ClojureScript

### ISSUE THREAD

**Issue by niquola** [jkk/honeysql#117]

**Comment by MichaelBlume** [comment]
I had a cljc fork working and passing tests in clojurescript at some point -- is there a need, do you think?

**Comment by niquola** [comment]
:+1: 

I need it in electron.io (nodejs) environment. Where could i find your fork? I could start from it.

**Comment by MichaelBlume** [comment]
Good luck =)

https://github.com/MichaelBlume/honeysql/tree/cljc

**Comment by MichaelBlume** [comment]
Do let me know how this goes =)

**Comment by ddellacosta** [comment]
Also maybe relevant: https://github.com/jkk/honeysql/pull/105

I haven't commented on that one because I'm kind of stumped as to whether or not this should be supported or not.  Can see arguments going both ways, but in the end if enough people find it useful seems like it may be worth incorporating...?

**Comment by niquola** [comment]
Thx, going to try :)

**Comment by rnewman** [comment]
Any news on this, @niquola or @MichaelBlume?

**Comment by rnewman** [comment]
I rebased @MichaelBlume's work onto current master, and I'm taking a look at why `lein test` fails.

https://github.com/rnewman/honeysql/tree/rnewman/rebase

**Comment by MichaelBlume** [comment]
I'm going to release this as 0.8.0 -- HoneySQL now requires Clojure 1.7.0 or above.
