### ISSUE TITLE
function call arguments and `if`

### ISSUE THREAD

**Issue by mattly** [jkk/honeysql#125]
so I'm trying to do `select sum(if(foo = 1, 1, 0)) as foo_count`, but it seems there's no sane way to represent this in honeysql without resorting to `sql/raw`: `(sql/call :sum (sql/call :if (sql/raw "foo = 1") 1 0))`. What I'd *like* to do (and what it seems like I should be able to do) for the `if` call is `(sql/call :if [:= :foo 1] 1 0)` but that formats into `if((=, :foo, 1), 1, 0)`. Is there a better way to do this? I couldn't find any examples of using `if`

**Comment by ddellacosta** [comment]
@mattly I'm having trouble figuring out if `if` or variations of are supported in ANSI SQL, so it may or may not be a candidate for inclusion as a patch.

Otherwise, this seems like a prime candidate for adding your own helper by adding (def)methods via fn-handler/format-clause.  You may want to take a look at the code in https://github.com/jkk/honeysql/blob/master/src/honeysql/format.clj for examples.  _Note to self: write up a better doc on how to do this_
