### ISSUE TITLE
`sset` with only one arg builds a value clause

### ISSUE THREAD

**Issue by caleb** [jkk/honeysql#126]
I'm not sure if this is correct, but I'm using honesql to generate SQL snippets and I noticed something strange.

When I call `sset` with one argument (my values map), I get a `:values` clause back instead of a `:set` clause.

```clojure
(sset {:a "b"})
> {:values {:a "b"}}
```

Here is the code from the `sset` function:

```clojure
(defn sset
  ([vs] (values nil vs))
  ([m vs] (build-clause :set m vs)))
```

Am I missing something?

-Caleb

**Comment by ddellacosta** [comment]
Don't think you're missing anything.  I'm guessing this is simply an oversight because of how infrequently one may use `sset` in the manner you are using it.  The generally assumption is that you'd be passing the helper your map as the first argument, like

```clojure
> (-> (update :foo) (sset {:a "b"})
{:update :foo, :set {:a "b"}}
>
```

I'm not sure there's a ton of value in fixing this--I'm more curious why there's a single arity version anyways...but I suppose a simple fix would be to call it with an empty map vs. what we have now:

```clojure
(defn sset
  ([vs] (sset {} vs))
  ([m vs] (build-clause :set m vs)))
```

Of course, you can get around this pretty trivially by doing that yourself:

```clojure
> (sset {} {:foo "bar"})
{:set {:foo "bar"}}
>
```
or for that matter

```clojure
> (assoc {} :set {:foo "bar"})
{:set {:foo "bar"}}
>
```

etc.

**Comment by caleb** [comment]
Okay, I admit it is a bit strange, but the README says:

> Order doesn't matter:

```
(= (-> (select :*) (from :foo))
   (-> (from :foo) (select :*)))
=> true
```

I actually forget why I was composing in this order before, but it seemed like it should work :) It's not a big deal, but I think it would be nice to fix this.
