### ISSUE TITLE
Prefix column names from joined tables to avoid ambiguity

### ISSUE THREAD

**Issue by theronic** [jkk/honeysql#127]
When you join two tables both with id columns, you'll get an "ambiguous column" error. But if you alias each table, the joined tables id column will be swallowed by any subsequent columns specified, which is quite unexpected and order-dependent.

How can HoneySQL return prefixed keywords for each aliased table, so that I don't manually have to specify each column I'm looking for?

E.g. 

```
(->
    (select :l.* :c.* [:c.id :line-id])
    (from [:lines :l])
    (join [:customers :c] [:= :l.customer_id :c.id]))
```

Where both the "lines" table and "customers" table have an ID column. In order to retain the joined "id" column from the "customers" table, I need to explicitly rename it. It would be great if I just got a map with prefixed keys according to aliases, or even got nested maps, e.g. `{:id 1 :customer {id 1 ...}}`

**Comment by jrdoane** [comment]
This would need to handled with whatever you're using for a database connection, wouldn't it? HoneySQL doesn't know the names of the fields of the tables you're referencing when you do something like ```:l.*``` so, it's not realistic to expect HoneySQL to be able to figure that out. At least in PostgreSQL, if you have a SELECT with multiple fields with the same name, it will return multiple fields with the same name. If you're using ```clojure.java.jdbc```, the default return is a vector of maps and the keys in a map are naturally unique. The optional ```result-set-fn``` and ```row-fn``` when using ```clojure.java.jdbc/query``` can give you control over how to handle re-mapping field names but, I would argue that this is outside the scope of HoneySQL. You could also utilize the ```as-arrays?``` optional parameter for the query function as well.

Either way, there are solutions to this but, none of them reside in HoneySQL because it's not capable of reading your database's schema. HoneySQL is for generating SQL, not reading your database and doing weird database-state related transforms on your queries. The only way to do this in HoneySQL is to ahead of time, query the names of all the fields on the tables you want and programically alias them to something unique based on table name or alias plus field name but, I would argue that's an imperfect solution.

This is a slight tangent but, this is why I've started opting for unique field names based on what it is, so instead of having a ```user``` table with an ```id``` field as primary key, I would use ```user-id``` or ```user_id``` instead because, you won't get this kind of conflict and if you do, it's reasonable to expect that two fields called ```user-id``` most definitely is probably referencing the same data.

**Comment by ddellacosta** [comment]
@pate do you feel jrdoane addressed this? I agree that this is a pain point but also agree with jrdoane that it's not really HoneySQL's purview.

**Comment by seancorfield** [comment]
`clojure.java.jdbc` handled this directly so I don't believe this is really a HoneySQL issue?

**Comment by seancorfield** [comment]
Closing for lack of a response.
