### ISSUE TITLE
How to compose joins?

### ISSUE THREAD

**Issue by pate** [jkk/honeysql#129]
How can I compose a join without overriding the previous join?

```
(def common-query
  (-> (select :*)
    (from :users)
    (join :roles [:= :roles.user_id :users.id]))

(-> common-query  ; the join here overrides the previous join
  (join :another-table [:= :another-table.user_id :users.id]))

```

**Comment by pate** [comment]
Figured out I can do this:

```
(merge-with concat common-query
    (-> (join [:another-table :at] [:= :at.user_id :users.id])
      (where [:= :users.id 123])))
```

Is this recommended practice?

**Comment by jrdoane** [comment]
I don't tend to use the helper functions directly. The query itself really is only a map that looks something like this with what you're doing:
```clojure
(def base-query
  {:select [:*]
   :from [:users]
   :join [:roles [:= :roles.user_id :users.id]]})

(def extra-table
  {:join [:another-table [:= :another-table.user_id :users.id]]
   :where [:= :users.id 123]})

(merge-with concat base-query extra-table)
```

You can concat JOINs and SELECT together but, extra thought would need to be put into merging where conditions since you would need to know if the two statements need to logically reduced to a single boolean value with an "OR" or an "AND" if there are two WHERE statements. I personally don't usually take two queries and merge them together, I build them up so, I would merely do something like this:

```clojure
(def base-query
  {:select [:*]
   :from [:users]
   :join [:roles [:= :roles.user_id :users.id]]})

(defn complete-query [user-id mp]
  (-> base-query
     (update-in [:join] #(concat % [[:another-table :at] [:= :at.user_id :users.id]]))
     (update-in [:where] #(let [q [:= :users.id user-id]] (if (nil? %) q [mp % q]))))

(complete-query 12345 :and)
```

I personally find it easier to think about composing queries when I just think of them as the bare EDN data structures. It's only a map of vectors. It's not too hard to just use ```update-in```, ```conj``` and, ```concat``` to do a lot of what you probably want to do but, that example above would allow you to have a WHERE on the base query and control how the WHERE statements get merged together.

I also usually don't end up altering JOINs very often. I usually have the from and the joins constructed ahead of time since there isn't usually a dependency on data. So something like this might have more utility because all of the non-changing parts of the query have been defined and all you have to do is assoc in a where but, when push comes to shove, you're doing the same thing.

```clojure
(def base-query
  {:select [:*]
   :from [:users]
   :join [:roles [:= :roles.user_id :users.id]]})

(def joined-query
  (update-in [:join] #(concat % [[:another-table :at] [:= :at.user_id :users.id]])))

(defn user-query [user-id]
  (assoc joined-query :where [:= :users.id user-id])
```

**Comment by ddellacosta** [comment]
@pate I would have written something like what jrdoane wrote--basically, treating HoneySQL query maps as Clojure data structures gives you the ultimate flexibility and is probably the most idiomatic approach.

Going to close this one since I think your question was answered, but let me know if not.
