### ISSUE TITLE
Possible bug generating SQL using the columns helper (lack of separator for MySQL)

### ISSUE THREAD

**Issue by mmower** [jkk/honeysql#139]
Hi

I had some code that looked like this:

``` clojure
(-> (h/insert-into (:table model))
  (h/columns (:attrs model))
  (h/values [(map #(get inst %) (:attrs model))])
  (sql/format :quoting :mysql :allow-dashed-names? true))
```

which was generating a statement like:

`["INSERT INTO`customer-segments`(`name` `exemplars`) VALUES (?, ?)" "Foo" "Bar"]`

(note the lack of a "," between name and exemplars)

you might wonder why I'd done that but I only remembered about values taking a map after I started trying to figure out why this was generating invalid SQL. Switching to:

``` clojure
(-> (h/insert-into (:table model))
  (h/values [inst])
  (sql/format :quoting :mysql :allow-dashed-names? true))
```

generates the correct SQL:

["INSERT INTO `customer-segments` (`name`, `exemplars`) VALUES (?, ?)" "Foo" "Bar"]

So it seems like when you use the columns helper directly the generated SQL is invalid for MySQL.

Or I've quite possibly missed something...

**Comment by MichaelBlume** [comment]
It looks like the columns helper does the right thing if you pass the
columns as varargs rather than as a single seq argument. Wonder if we
should make it behave correctly when called with a list or if this would
break something else.

**Comment by seancorfield** [comment]
My initial reaction on stuff like this is "Nope, make folks use stuff properly", but if you are generating a collection of column names, you would need to `(apply columns m coll-of-cols)` and then you lose the ability to easily thread through with `->`. That made me think maybe this would be a good case for allowing a collection of column names and automatically unwrapping them. But then `values` requires exactly two arguments: a SQL structure and a vector of vectors of values or a vector of maps (of columns and values) so it does _does_ allow for generated values. If you mistakenly call `values` with incorrect argument types, you get an exception.

So that persuades me that mistakenly calling `columns` with incorrect arguments should throw an exception raw than either silently generating bad SQL (which is very unintuitive) or attempt to support two different types of argument formats.

@mmower How would you have felt if you'd gotten an exception from `columns` indicating that it requires expanded column names instead of a collection? (and so you'd need:
```
(-> ... (as-> sql (apply columns sql (:attrs model))) ...)
```

**Comment by seancorfield** [comment]
Since similar checks were added elsewhere for 0.9.4, I'm targeting this for 0.9.5.
