### ISSUE TITLE
CLJS tests do not run in Travis

### ISSUE THREAD

**Issue by MichaelBlume** [jkk/honeysql#161]
Right now we only automatically run tests in Clojure, not Clojurescript. It'd be nice to fix this. I'm not very familiar with the cljs ecosystem, so the Right Thing is not immediately obvious to me.

**Comment by MichaelBlume** [comment]
@rnewman would you be willing to check and see if this is something you can get working? If not, no worries.

**Comment by rnewman** [comment]
Sorry, @MichaelBlume; I'm not currently doing any ClojureScript work.

**Comment by seancorfield** [comment]
Do we have any sense of how many CLJS users of HoneySQL exist? I was actually surprised that CLJS was supported at all, given the target being JDBC on the JVM -- or so I thought?

I have the CLJS tests running locally (but it was guesswork because there's no *Developer Information* section in the README -- @MichaelBlume could you write something up so I can check I'm doing the right thing?). So far, I've found:
```
lein test-readme 
lein with-profile midje test
lein doo node test once
```

**Comment by arichiardi** [comment]
I am running both using lumo and vanilla cljs. Will try to have a look at well.

**Comment by arichiardi** [comment]
Right, lumo tests are green, at least they were, so I guess it is just a matter of understanding the problem with vanilla then.

**Comment by seancorfield** [comment]
I eventually figured out that the tests can/should be run like this: https://github.com/jkk/honeysql/blob/master/run-tests.sh

That's also what's in `.travis.yml` and the build is passing so I'm going to declare this fixed.

**Comment by seancorfield** [comment]
Oops, wrong issue.
