### ISSUE TITLE
Passing in a custom `defrecord` as a param results in `()`

### ISSUE THREAD

**Issue by yatesco** [jkk/honeysql#177]
I have a `defrecord MyCustomType` which returns a `java.sql.Timestamp` through extending `clojure.java.jdbc/ISQLValue`.

The following `(jdbc/query db ["select count(0) from some_table where some_column>?" (MyCustomType. ...)])` works but `(hsql/format {:where [:> :some_column (MyCustomType. ...)]})` returns `"WHERE some_column < ()"`

My assumption was that parameters were passed straight through but something seems to be (mis)interpreting instances of `MyCustomType`. 

Is there a magic protocol I need to implement to allow `honeysql` to understand `MyCustomType`?

Thanks!

**Comment by MichaelBlume** [comment]
So we could have honeysql check whether an object `satisfies?` that protocol, though we'd have to make that check conditional on whether the jdbc lib appears to be present at all

**Comment by yatesco** [comment]
I found implementing the [`honeysql.format/ToSql`](https://github.com/jkk/honeysql/blob/a707222d53ebe512ef47b6d771901cd9d75c4cc0/src/honeysql/format.cljc#L94) protocol works for now. 

Is that protocol a stable extension point?

**Comment by MichaelBlume** [comment]
Yes, definitely

**Comment by yatesco** [comment]
Issued a PR which updates the front page.

**Comment by emidln** [comment]
I'm late here (as usual), but I was under the impression this was already solved more generically via `honeysql.format/Value` and its constructor `honeysql.format/value`. 

```(hsql/format {:where [:> :some_column (honeysql.format/value (MyCustomType. ...)]})``` would then return ```"WHERE some_column < ?"``` and defer to the underlying (JDBC) implementation for converting MyCustomType. This is much preferable to implement `ISQLValue` which is a well-known extension point rather than our own `ToSQL`, especially in applications that mix ways of building queries (inline SQL or HugSQL for relatively static queries; HoneySQL for more dynamic queries).

**Comment by yatesco** [comment]
Hi @emidln. I think I will always argue for extending a protocol once rather than calling `honeysql.format/value` everywhere. Same for extending `ISQLValue` for date/times rather than the more painful `(java.sql.Timestamp. (.getTime....))`.

If it was Christmas :-) then  `honeysql` should remove the need to do anything special and pass unrecognised things to `clojure.java.jdbc`, or at the very least throw a meaningful exception.

**Comment by emidln** [comment]
The issue is when our custom type is a record or something else map-like or array-like. The way HoneySQL handles maps is to treat them as an embedded HoneySQL map resulting in a subquery. I don't think it's reasonable to require that a HoneySQL query map be a certain type (perhaps spec/schema could help here by enforcing structure in the future) or not be a certain type. 

Further, when we consider non-standard or custom data types at the db-level, it makes no sense to extend via HoneySQL unless your type is essentially an alias (i.e. can be represented as a common type JDBC already knows about). Anything moderately complex (i.e. my record `Foo` into a `jsonb` column`) requires using `ISQLValue` anyway, and pushing an alternative to "simple" cases to get implicit conversion feels like it will just serve to confuse.

In fact, the only time you actually need to do anything other than wrap with `ISQLValue` is when your custom type is map-like or array-like. If you write:

```clojure
(deftype Point [x y])                     
(honeysql.core/format (-> (insert-into :points) (values [{:point Point}])))
```
which returns something like ```["INSERT INTO points (point) VALUES (?)" #object[user.Point 0x5d4185cf "user.Point@5d4185cf"]]```
HoneySQL will happily pass through your custom `Point` to clojure.java.jdbc which can then use ISQLValue to turn it into the appropriate database type. If instead I wrote:

```clojure
(defrecord Point [x y])
(honeysql.core/format 
  (-> (insert-into :points)
        ;; this is going to treat Point as a subquery and not do what we want 
        (values [{:point Point}])))
```

which returns something like ```["INSERT INTO points (point) VALUES (( ))"]```

Using `honeysql.format/value` for disambiguation between map or array-like values and subqueries gives us tremendous flexibility to compose arbitrarily complex queries. I use such functionality constantly both during my repl-driven development process and for more complex user interfaces.

For the record, I also implement `JodaTime` support via `ISQLValue`, but `org.joda.time.DateTime` is not a map-like object. Since it's not a map, it is passed along as a parameter to the JDBC layer. I also implement json/jsonb support via `ISQLValue` and use `honeysql.format/value` to disambiguate json objects or json arrays from subqueries and aliases.

**Comment by yatesco** [comment]
Would it be reasonable then for HoneySQL to assume anything _other_ than
a non-record map should be passed through untouched?
How likely is it for people to wrap a 'HoneySQL' map in a defrecord? I
can't imagine it very likely...

--
  Colin Yates
  colin@colinyates.co.uk



On Mon, 28 Aug 2017, at 03:47 PM, Brandon Adams wrote:
> The issue is when our custom type is a record or something else map-
> like or array-like. The way HoneySQL handles maps is to treat them as
> an embedded HoneySQL map resulting in a subquery. I don't think it's
> reasonable to require that a HoneySQL query map be a certain type
> (perhaps spec/schema could help here by enforcing structure in the
> future) or not be a certain type.> Further, when we consider non-standard or custom data types at the db-
> level, it makes no sense to extend via HoneySQL unless your type is
> essentially an alias (i.e. can be represented as a common type JDBC
> already knows about). Anything moderately complex (i.e. my record Foo
> into a jsonb column) requires usingISQLValue` anyway, and pushing an
> alternative to "simple" cases to get implicit conversion feels like it
> will just serve to confuse.> In fact, the only time you actually need to do anything other than
> wrap with ISQLValue is when your custom type is map-like or array-
> like. If you write:> (deftype Point [x y]) (honeysql.core/format (-> (insert-into :points)
> (values [{:point Point}])))> 


> which returns something like ["INSERT INTO points (point) VALUES (?)"
> #object[user.Point 0x5d4185cf "user.Point@5d4185cf"]]>  HoneySQL will happily pass through your custom Point to
>  clojure.java.jdbc which can then use ISQLValue to turn it into the
>  appropriate database type. If instead I wrote:> 


> (defrecord Point [x y]) (honeysql.core/format (-> (insert-into
> :points)  ;; this is going to treat Point as a subquery and not do
> what we want  (values [{:point Point}])))> which returns something like ["INSERT INTO points (point)
> VALUES (( ))"]> Using honeysql.format/value for disambiguation between map or array-
> like values and subqueries gives us tremendous flexibility to compose
> arbitrarily complex queries. I use such functionality constantly both
> during my repl-driven development process and for more complex user
> interfaces.> For the record, I also implement JodaTime support via ISQLValue, but
> org.joda.time.DateTime is not a map-like object. Since it's not a map,
> it is passed along as a parameter to the JDBC layer. I also implement
> json/jsonb support via ISQLValue and use honeysql.format/value to
> disambiguate json objects or json arrays from subqueries and aliases.> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/jkk/honeysql/issues/177#issuecomment-325374691

**Comment by emidln** [comment]
I'm unsure how much this is actually used in the wild. I personally
wouldn't have a problem with requiring the clauses to be `(and (map? x)
(not (record? x))`, but this would be a breaking change (and further
considered by the community).

An alternate way to maintain compatibility would be documenting the way to
opt out of formatting for your custom types. The internal Value provides
the example:

```clj

(defrecord MyAwesomeRecord [my-value meta-info]
     honeysql.format/ToSql
      (to-sql [this] (honeysql.format/add-anon-param my-value)))

```

The README probably should at minimum be updated with a caveat and that
last method (which works now) since it's what meshes with the rest of the
advice we see around the web regarding clojure.java.jdbc (w.r.t using
jdbc's ISQLValue and IResultSetReadColumn).

**Comment by MichaelBlume** [comment]
What do you think of doing something like this https://github.com/jkk/honeysql/compare/master...MichaelBlume:unwrap-jdbc?expand=1#diff-c131aed806e733e9b69514f8243ab824

so that ISQLValues Just Work?

**Comment by yatesco** [comment]
That works for me.

**Comment by MichaelBlume** [comment]
Unfortunately it would break ToSQL as an integration point when I just said that was fine, but we could bump the version and call it out in CHANGES
