### ISSUE TITLE
Question: Parse a SQL string into HoneySQL?

### ISSUE THREAD

**Issue by raspasov** [jkk/honeysql#182]
First things first: This library is the best thing that ever happened to SQL! Great work! :)

Use case: Different software gives you SQL queries as a string after, let's say, you built up a filter in the UI - either join or a complex WHERE clause. Sometimes it's useful and time-saving to be able to turn that string into a HoneySQL data structure instead of re-typing it all! I believe "parsing" would be the right word for this. I tried looking for it - let me know if I missed something :). 

Again thank you for the great library!

**Comment by MichaelBlume** [comment]
This sounds pretty hard but also really useful. If people want to take it on, I'd be excited to merge it.

**Comment by seancorfield** [comment]
My biggest concern would be around vendor-specific SQL: that couldn't be parsed back down to HoneySQL data structures -- because HoneySQL tries hard to be vendor-neutral. I think it's an interesting idea but I don't think it belongs in HoneySQL itself. Perhaps a new companion library could be created that deals with this (and perhaps it would need to have a parser for each database dialect supported)?

@raspasov Do you have any objection to me closing this as out of scope?

**Comment by seancorfield** [comment]
Closing for lack of response (as out of scope).

**Comment by razum2um** [comment]
Huge thanks for the lib as well! I just love to handle "draft/base" sql queries like `assoc sql :where` because `String`s suck. 

Just briefly ensured that there's no pure clj sql parser, (obviously, heh). There're lots of stuff like https://github.com/JSQLParser/JSqlParser pushing us back to nice-old-hated-java-class-per-node approach and separate pure-js parser like https://github.com/JavaScriptor/js-sql-parser

Leveraging a library seems easier, but I suggest you'd vote for pure clj parser. Any other thoughts about how this could be done to get things done? Besides, another question what's your primary case - composing sqls in repl/clj-editor using the lib from 0 or translate from strings?

Btw, just noticing, https://github.com/jkk/honeysql/issues/192 imo related

**Comment by seancorfield** [comment]
Yeah, as noted in #192 one of the big problems is that every DB has extensions to ANSI SQL so there's no standard way to parse SQL strings. In addition, as I found out with `update`/`set`, different DBs actually have different syntax for the same statement :(

Even if it was feasible in general, it would be outside the scope of HoneySQL.

**Comment by razum2um** [comment]
It's clear about dialects, but I expected compatibility at least on SQL-2003 standard, basic things, because e.g. `with recurcive` or postgres' jsonb syntax are out of scope of `assoc`-ing, for me at least. FWIW, personally me 90% `assoc`-ing the `where` part

Btw, note that at least [postgresql json syntax got into last standard](https://www.postgresql.org/docs/12/biblio.html#SQLTR-19075-6) 🎉

Also, could you post full example with `update / set` you mentioned?

**Comment by seancorfield** [comment]
Given how prevalent the use of non-ANSI-standard syntax seems to be -- based on all the issues and support I've had to deal with in nearly nine years of maintaining `clojure.java.jdbc` -- a parser for just the ANSI subset of that wouldn't be very useful and any such parser project would face constant requests for enhancements. Anyone is welcome to try to create such a project but it is out of scope for HoneySQL.

As for the `update` / `set` issue, search through the closed issues -- it originally cropped up as a "fix" for one database dialect which broke another database dialect, so I ended up adding `set0` and `set1` to allow for both dialects to be supported.
