### ISSUE TITLE
Should "inline" mean "raw and unparameterized"?

### ISSUE THREAD

**Issue by xiongtx** [jkk/honeysql#221]
## Problem

Inline `nil` values are not turned into `NULL`, resulting in surprising behavior:

```clojure
(require '[honeysql.helpers :as h])
(require '[honeysql.format :as sqlf])

(-> (h/insert-into :foo)
    (h/values {:a (sql/inline 1) :b (sql/inline nil)})
    sqlf/format)
;; => ["INSERT INTO foo VALUES (a, 1), (b, )"]    ; Invalid!
```

It seems that "inline" roughly means "raw and unparameterized", which complects two concepts. Often I want a single unparameterized string that can be concatenated with other strings to form a more complex (usually vendor-specific) command, but still treat values as non-raw.

While in this case `nil` values are never parameterized, the general idea of separating concerns still appears valid.

**Comment by seancorfield** [comment]
No, `#raw` means raw -- a string that is placed directly into the SQL. `#inline` means inline value -- a value that is not lifted out as a parameter. `#inline nil` should almost certainly produce `NULL` so that's definitely a bug.

**Comment by seancorfield** [comment]
This will be in the 0.9.4 release.

**Comment by seancorfield** [comment]
Yeah, strings are a bit of an issue for both `#inline` and `#raw` with parameters. Both of those were added to "work around" the normal machinery of building data structures with keywords and parameters and I don't think they were really analyzed for all the edge cases. You're right that there's no string escaping in HoneySQL (yet) and that's because it isn't needed for the parameterized cases -- because JDBC takes care of it -- and it wasn't really needed for the pure `#raw` case since that was just a literal (Clojure) string that was passed through and it was up to the user to get that right.

When `#inline` was introduced, that model broke a bit. When I introduced parameters for `#raw`, that model broke a bit more. At this point, I don't want to mess with `#inline` any further: you can get a SQL string by doing:
```clojure
(-> (h/select [#sql/inline "'foo'" :a])
    (h/from :mytable)
    (sqlf/format))
```
I need to give some serious hammock time to figure out a better overall solution to raw/inline (and also review the other reader literals).

**Comment by xiongtx** [comment]
To _properly_ handle all inline values, we'd need all the conversions from Clojure values to string representations present in `clojure.java.jdbc` and use them in HoneySQL. I.e. whatever `clojure.java.jdbc` does to turn `["... ? ..." <param>]` into a single string, that'll need to be replicated here.

**Comment by seancorfield** [comment]
That's not how `clojure.java.jdbc` works. It doesn't convert values to SQL strings -- it simply passes them as values into `PreparedStatement`s as `Object`s. It does no conversion at all really: JDBC handles it.

And if you let HoneySQL lift Clojure values out as parameters -- the default value -- then it's all just handled automatically by JDBC. 

`#raw` takes Clojure strings and just drops them into the SQL string "as-is" so it's up to users to get that right. `#inline` is kind of odd because it takes Clojure values and simply calls `str` on them and drops them into the SQL string. Which is why `nil` didn't work: `(str nil)` is just `""` -- an empty string. It's also why parameters in `#raw` don't work for strings (and also wouldn't work for `nil` I suspect).
