### ISSUE TITLE
2.0: revisit merge vs non-merge helpers

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#260]
The non-merging nature of helper functions seems to catch a lot of people out. In my experience, I pretty much always want merging behavior, rather than overwriting behavior. Should 2.0 have that behavior as the default (and perhaps deprecate all the `merge-` variants or just drop them altogether)?

The overwriting behavior could be opted into by threading the query through `(dissoc :join)` etc.

**Comment by stathissideris** [comment]
You mention `(dissoc :join)` but from reading the documentation I got the impression that the underlying map representation is undocumented and as such, it can change without warning. Because of that, I generally avoid touching the maps and try to do everything via the functions (as much as possible). Am I right in following this strategy? If so, the `dissoc` semantics should probably be "officially" supported by a new function.

**Comment by stathissideris** [comment]
More to the point of the ticket, I was never confused about merging and non-merging. I've seen developers who were unaware about the `merge-` variants and would end up reimplementing some version of them to manipulate the map representation. If the map representation was to become "official" (with a spec and everything!) maybe it would make sense to drop the "constructor" variants of the functions and just keep the merge variants (but I like the `merge-` prefix), because then it would be clear that in one occassion you're writing a data literal, and when merging you're manipulating it in some non-trivial way.

**Comment by seancorfield** [comment]
I think you're right that the underlying map representation is undocumented but I know a _lot_ of people rely on it and actively _dislike_ the helper functions.

I'm beginning to come around to the idea of a ground-up rewrite of HoneySQL (in new namespaces) such that the map representation will become standard -- documented and fully covered by Spec -- and the format function will be dialect-aware since that's been one of the biggest problems over the years. Then a new set of helpers can probably be generated from the specs (and will all be merge-by-default).

The current extension mechanism is pretty clumsy -- or at least a lot more verbose than I would like -- and the call and raw syntax stuff is all a bit of a hacky mess at this point.

It's a long-term goal. Still requires a lot of hammock time.

**Comment by niquola** [comment]
Take a look at https://github.com/niquola/dsql - probably you can merge some ideas. If you like the approach - I can help you with implementation.

**Comment by seancorfield** [comment]
Now that I have broken ground on the 2.x rewrite it has solidified my thinking that documenting and possibly Spec'ing the data DSL will be a core focus and my (current) plan is to figure out a way to auto-generate a helper function for every known piece of syntax (including auto-generating helpers for any new clauses that users register). That would mean every piece of syntax would have a simple, consistent helper and they would all have "merging" behavior -- that's part of the puzzle I haven't quite figured out yet since the merging behavior is slightly different across the various pieces of syntax.

**Comment by seancorfield** [comment]
v2 helpers are all "merge" by default. Anyone wanting the overwrite behavior will need to explicitly `dissoc` a key.

The v1 data structure is almost entirely preserved for v2 and will be documented and specified before release.
