### ISSUE TITLE
Add dependency on org.clojure/java.jdbc

### ISSUE THREAD

**Issue by quanticle** [jkk/honeysql#273]
I just brought in HoneySQL as a dependency on a new Clojure project and I received the following error when I started my REPL: 

```
#error {
 :cause Could not locate clojure/java/jdbc__init.class, clojure/java/jdbc.clj or clojure/java/jdbc.cljc on classpath.
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling at (guaranteed_rate_assignment/core.clj:1:1).
   :data #:clojure.error{:phase :compile-syntax-check, :line 1, :column 1, :source <redacted>/core.clj}
   :at [clojure.lang.Compiler load Compiler.java 7648]}
  {:type java.io.FileNotFoundException
   :message Could not locate clojure/java/jdbc__init.class, clojure/java/jdbc.clj or clojure/java/jdbc.cljc on classpath.
   :at [clojure.lang.RT load RT.java 462]}]
```

Adding `[org.clojure/java.jdbc "0.7.11"]` to the dependencies section in my `project.clj` fixed the issue. It looks like the JDBC classes were moved out of Clojure core and into `org.clojure/java.jdbc`. It would be nice if HoneySQL added this dependency itself to prevent users from having to deal with mysterious classpath errors.

**Comment by seancorfield** [comment]
The JDBC classes have never been part of Clojure core. I took over maintenance of `clojure.contrib.sql` when the monolithic Contrib was broken up for the Clojure 1.3 release and renamed it `clojure.java.jdbc` -- it has always been a Contrib project. `clojure.java.jdbc` is no longer maintained -- `next.jdbc` is the 1.0 release that `clojure.java.jdbc` never got (because it required breaking compatibility).

HoneySQL is not tied to a JDBC library. You can use it with `clojure.java.jdbc` and with `next.jdbc`. There are other JDBC libraries it can be used with too.

Therefore it makes no sense for HoneySQL to depend on `clojure.java.jdbc` -- and I would recommend you migrate to `next.jdbc` at this point anyway.
