### ISSUE TITLE
2.0 Gungnir currently hooks into fn-handler multimethod -- how will that work in V2?

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#276]
See https://github.com/kwrooijen/gungnir/blob/8815a230fd439a97e1db970ad89b08a323b625db/src/clj/gungnir/query.clj#L295-L363

The high-level need is to be able to apply before read/before save transformations to column values as part of the SQL building code -- essentially spotting column names that line up with parameter values and invoking the transformations as part of that.

**Comment by seancorfield** [comment]
@kwrooijen Looking over Gungnir's code, it looks like you only need to be able to hook into the infix operator portion of the expression handling? If that's the case, then providing a hook into the formatting engine around this line would seem to satisfy your needs: https://github.com/seancorfield/honeysql/blob/v2/src/honey/sql.cljc#L1112

I'm thinking of a dynamic var, bound to `identity` by default, that processes the whole `expr` and rebinds `expr` prior to processing the actual `op` value?

**Comment by kwrooijen** [comment]
Hey Sean, my laptop is currently broken and I'm in the middle of a move. I'll get back to this as soon as I can😬. Thanks for looking into this!

**Comment by seancorfield** [comment]
Sorry to hear that -- and good luck with your move! No rush on feedback. I'm pretty sure this will be a purely accretive change so it's not tied to HoneySQL V2's prerelease stages.

**Comment by kwrooijen** [comment]
Sorry for the late reply.

It looks like the line you're referring to is a bit off now because of new commits. But I think you're pointing to the `format-expr` function?

> Looking over Gungnir's code, it looks like you only need to be able to hook into the infix operator portion of the expression handling?

You're right, I'm only applying these transformations to comparison infix operators. I'm not sure how this `format-expr` works but I had to create a bit of a "hack" to make sure transformations only applied once (see https://github.com/kwrooijen/gungnir/blob/8815a230fd439a97e1db970ad89b08a323b625db/src/clj/gungnir/query.clj#L297-L303). 

For this to work in Gungnir, I'd need the following:
1. If you can guarantee that transformations are only applied once then a dynamic var should work perfectly. 
2. I'd need the entire expression with all values + operator (e.g. `[:= :user/age 20 20]`) in my transformation function.

Let me know if these requirements are ok for you and thanks for putting the time into this.

**Comment by seancorfield** [comment]
The comparison ops are not variadic in V2 -- only `:and :or :+ :* :||` are currently variadic -- so I think most of your `recurred?` logic wouldn't be necessary. I have to be honest and say I don't really understand exactly what Gungnir is trying to do, but I _think_ given `[:= :email "foo"]` and a `before-read` of `str/lower-case`, it would want to produce `["email = ?" (str/lower-case "foo")]` -- is that right?

But it doesn't look like the operator matters (beyond it being a comparison op) so if you were called with any `[op x y]` expression -- prior to transformation to SQL -- you could either return the expression or transform it if `op` is a comparison and either `x` or `y` is an `ident?` and the other one is a value?

What do you do for expressions like `[:= :email [:concat id "@gmail.com"]]` -- also, what about `[:= "foo" :email]` -- it seems like the latter would not be handled by Gungnir since it seems to key off the first operand to find transformations, but I'm not sure what it would do with the former?

**Comment by seancorfield** [comment]
Given the open questions, I'm going to move ahead with an RC for 2.0 and target this integration for 2.1. I think there's a lot of scope for interesting integrations beyond Gungnir but I want to make sure that whatever I add satisfies _at least_ Gungnir's requirements.

**Comment by kwrooijen** [comment]
Hi Sean. I just released a new version of Gungnir with HoneySQL 2. I was able to resolve this without additional code for Honeysql. I'll close this issue now. Thank you for you insight!

Edit: Nevermind. I can't close issues :). Feel free to close this!

**Comment by seancorfield** [comment]
That's great to hear! Congrats!
