### ISSUE TITLE
SQL Injection in dynamic columns created with the keyword function

### ISSUE THREAD

**Issue by rbobrowicz** [jkk/honeysql#316]
I was playing around with honeysql yesterday and noticed that if you create a keyword from a string using `keyword` you can inject sql into column/table names. Minimal example:

```clojure
(def sort-column "foo; select * from users")
(-> {:select [:foo :bar]
     :from [:mytable]
     :order-by [(keyword sort-column)]}
    sql/format)
=> ["SELECT foo, bar FROM mytable ORDER BY foo; select * from users"]
```

This could easily happen if situations where, for example, you have user defined sorts being passed in as strings. Is this something that honeysql should be trying to catch? Or is it more of a "user beware" situation? Should it be called out in the README as potentially dangerous? I scanned it, but couldn't find anything about this case.

**Comment by seancorfield** [comment]
For some database drivers, that will fail to execute -- some (most?) drivers default to only allowing one SQL statement per `execute()` call and with MySQL at least you have to explicitly enable multi-statement execution (and there are caveats in the MySQL docs about not doing that precisely because of the risk of SQL injection!).

That said, HoneySQL certainly could check anything that is intended to be an "entity" and throw an exception if it contains "suspicious" characters -- I think there would need to be an option to turn it on/off because I'm sure there are HoneySQL users who are relying on turning some weird strings into keywords, precisely because they can currently rely on them just being embedded into the generated SQL (yes, they should use `:raw` but...)

I'll give it some thought. It won't be changed for 1.0 at this point but I may well add a check into 2.0.

**Comment by seancorfield** [comment]
Check on entity name added to V2. Currently, that check cannot be turned off.
