### ISSUE TITLE
Add a global quoting option

### ISSUE THREAD

**Issue by tomconnors** [jkk/honeysql#349]
It would be handy if honeysql exposed a function for globally controlling whether or not to quote, since setting the dialect w/ `set-dialect!` doesn't do that.

**Comment by seancorfield** [comment]
I'll give this some thought.

My initial reaction is no -- I don't want to add a global quoting flag that would interact with what happens when you specify `:dialect` and/or `:quoted` as options to the `format` function.

Right now, if you specify `:dialect` as an option to `format`, you can still opt out of quoting by _also_ passing `:quoted false`, or you can specify `:quoted true` to opt in if you are _not_ passing in `:dialect`. The principle behind that is quoting is optional and you opt into it explicitly, either by overriding the default dialect for a specific call or overriding the default quoting for a specific call.

That's also why setting a dialect globally at startup does not opt you into quoting -- and the global dialect setting is mostly a performance optimization over passing it as an option to `format` but also recognizes that most programs only interact with one type of SQL database.

**Comment by seancorfield** [comment]
I've added an optional `:quoted true` (or `:quoted false`) argument to `set-dialect!`.

**Comment by tomconnors** [comment]
Thanks!
