### ISSUE TITLE
Possible migration guide improvements

### ISSUE THREAD

**Issue by mrkam2** [jkk/honeysql#358]
Things I ran into during migration to v2 that would be nice to add to the migration guide:
- `format-predicate` is now `format-expr`,
- `offset` and `limit` helpers no longer support `nil` values,
- it wasn't straightforward to find replacements for the API that was gone, partially because the migration guide doesn't reference specific API replacements. I. e. searching by the following API words gave no results: `ToSql`, `fn-handler`, `to-sql`, `add-anon-param`, `format-predicate`. Would've been nice to indicate specific APIs and their replacements.
- For example, `ToSql` protocol used to nicely take care of specific values (clojure records) passed as parameters in the queries. Now these parameters need to be wrapped into `:lift`. So what previously was addressed at a library/protocol level, now requires updates in all the queries. Maybe a new `register` function can be added that handles specific types?
- `[:raw` may require extra square brackets as it can get into a conflict with other vector forms supported by the DSL, such as in `select` clause where it can result in `SELECT raw AS foo` instead of `SELECT foo`. The bottom line is that this is how many brackets are needed for `:raw` in `SELECT` clause it work: `{:select [[[:raw "a"]]]}` I'm curious whether there are any other ways to avoid this ambiguity.

**Comment by seancorfield** [comment]
`format-expr` is not quite the same as `format-predicate` but will substitute for it in most cases. I don't know that `format-predicate` was ever really documented, but `format-expr` is: https://cljdoc.org/d/com.github.seancorfield/honeysql/2.0.783/api/honey.sql#format-expr

The v2 API is thoroughly documented. A lot of what you're referring to in v1 was undocumented and/or internal implementation details -- so it isn't really possible to provide a 1:1 migration guide for that stuff.

The `select`/function call issue is explained in the documentation, but I'm always happy to look at specific proposed changes to improve things.

**Comment by mrkam2** [comment]
> I don't know that `format-predicate` was ever really documented

Does this count as documentation? https://cljdoc.org/d/honeysql/honeysql/1.0.461/api/honeysql.format#format-predicate

> A lot of what you're referring to in v1 was undocumented and/or internal implementation details

Could you please be more specific?

`ToSql`: https://cljdoc.org/d/honeysql/honeysql/1.0.461/doc/readme#why-does-my-parameter-get-emitted-as-
`fn-handler`: https://cljdoc.org/d/honeysql/honeysql/1.0.461/doc/readme#extensibility
`to-sql` is given as an example in both of these.

**Comment by seancorfield** [comment]
Almost none of the public vars had docstrings so, no, that does not count as "documentation". There was nothing beyond the readme and the source code for the 1.x codebase, unfortunately, and the general lack of docstrings and the very patchy coverage of things in the readme makes a 1:1 migration guide pretty much impossible -- as I said above.

The migration guide says, of the v1 API: "The array, call, inline, param, and raw functions have all become standard syntax in the DSL as functions (and their tagged literal equivalents have also gone away because they are no longer needed)." And of the extension mechanism, it says this in the opening paragraph: "HoneySQL 1.x's extension mechanism required quite a bit of internal knowledge (clause priorities and multiple multimethod extension points). It also used a number of custom record types, protocols, and data readers to provide various "escape hatches" in the DSL for representing arrays, function calls (in some situations), inlined values, parameters, and raw SQL, which led to a number of inconsistencies over time, as well as making some things very hard to express while other similar things were easy to express." I have no idea how people were using the (poorly documented) extension machinery of v1 -- and the v2 extension mechanism is designed and documented from the ground up using a very different approach.

This is why I made sure that people can continue to use v1 alongside v2 and migrate things as and when they needed to, on a call-by-call basis, so no one is _forced_ to change their code if they don't want to.

If you have specific proposed wording changes for the migration guide, feel free to submit one or more PRs.
