### ISSUE TITLE
uuids should be formatted as strings

### ISSUE THREAD

**Issue by mccraigmccraig** [jkk/honeysql#385]
as this fragment shows:
```
(sql/format {:values [["abc'def" (java.util.UUID/randomUUID) 42 nil]]} {:inline true})
;; => ["VALUES ('abc''def', c28fa6e0-8986-11ec-8ca3-a50d2de755f7, 42, NULL)"]
```
`java.util.UUID` instances are formatted without quotes - they should be quoted as a string, at least for postgresql

a possible wrinkle: postgresql seems to like its uuids to be formatted as strings in queries. i don't know if that is universal. i do know that cassandra/cql (which is roughly a sql subset), takes its uuids without string quotes. if that pattern is repeated in any other real sql databases then maybe uuid quoting needs to vary per backend

**Comment by seancorfield** [comment]
I don't think many people use `:inline true` except for getting SQL to paste into their console tool because it's potentially dangerous (SQL injection) if the inline encoding doesn't correctly escape quotes etc, so I'm going to just treat this as a bug and fix it by wrapping the string version of the UUID in single quotes.

If anyone using `:inline true` with a different database gets tripped up by it, I'll make it dialect specific.

Right now, PostgreSQL is essentially the default dialect (really ANSI, but with PG's extensions overlaid) and there's no dialect for Cassandra (I don't even know what it's entity quoting strategy is).

**Comment by seancorfield** [comment]
A new SNAPSHOT build should be available on Clojars in a few minutes or you can depend on that SHA as a git dep. If you need a full Clojars release instead, LMK and I'll cut a new release.
