### ISSUE TITLE
Quoted identifiers should have quote characters within them escaped

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#394]
Started in https://clojurians.slack.com/archives/C03RZGPG3/p1647861579763639

```clojure
=> (sql/format {:update :table :set {"foo-bar" 1 "baz/quux] = (DELETE FROM users), [x" 2}} {:dialect :sqlserver})
["UPDATE [table] SET [foo-bar] = ?, [baz/quux] = (DELETE FROM users), [x] = ?" 1 2]
```

As can be seen from the above, if user input makes its way into the SQL map as an identifier (column name in this case), it will create an opportunity for SQL injections.

I mentioned in the Slack thread that I don't think it's a job for HoneySQL. But after looking at how some databases handle it, it actually seems much more straightforward than I though. Basically, to avoid an injection, every user-controlled identifier must be quoted and every symbol within that identifier that closes the quoting must be doubled. So if an identifier will be quoted with `"`, all `"` within it must be replaced with `""` prior to quoting. And if it's `[]`, then all `]` must be replaced with `]]`.

**Comment by holyjak** [comment]
Honey already supports escaping identifiers with `(honey/format ... {:quoted true})` so this would imply the addition of checking the identifiers and replacing the quote within them, correct?

**Comment by p-himik** [comment]
`{:quoted true}` enables quoting, but not escaping. It will not affect the example SQL statement above at all, in part because string identifiers are always quoted - even if you pass `{:quoted false}`.

**Comment by holyjak** [comment]
I see. Automatically escaping the quote character inside should-be-identifiers when either using string identifiers or explicitely asking for `:quoted true` makes sense to me. It looks as a reasonable security choice.

**Comment by seancorfield** [comment]
It doesn't help anyone who isn't quoting identifiers so escaping the (closing) quote character inside a quoted identifier feels like a band-aid to me: it potentially stops some injections for people who are making sure they quote all the time, but the underlying problem is really that "suspicious" characters are getting into the SQL at all.

HoneySQL already throws an exception if a would-be identifier contains `;` to prevent the meme-like `foo; drop table users` attack but I suspect also throwing if an identifier includes a space might catch many more such attempts (it would catch the OP example here, regardless of quoting) -- but I also suspect that some people legitimately do have database columns with spaces in their names (ugh!) and I don't want to break their code.

**Comment by p-himik** [comment]
> It doesn't help anyone who isn't quoting identifiers

IMO anyone who allows user input to be used as identifiers _must_ quote them and escape them. There's simply no reason not to. This issue is specifically for that case.
And when user input doesn't make its way to identifiers, the developer should be responsible for what they put there and whether they quote+escape it or not.

So the proposed solution is to just automatically escape all identifiers whenever quoting is used. Then the developer has reasonable amount of control and a reasonable affordance for safety. (perhaps there should be a warning to enable quoting if a string identifier is used)

**Comment by seancorfield** [comment]
Fair enough. I'll update the summary of this issue to be a bit more specific then -- and this particular change is fairly straightforward. I'll give the documentation some thought in that area too.

**Comment by seancorfield** [comment]
It turns out HoneySQL 1.x used to do this so now HoneySQL 2.x does exactly the same as HoneySQL 1.x did 😄
