### ISSUE TITLE
Documentation wrongly suggest to use vector for :insert-into

### ISSUE THREAD

**Issue by raicotop** [jkk/honeysql#410]
I was working with the library and used something very similar to:
https://github.com/seancorfield/honeysql/blob/91e75a7edfae86995f607fdc6ddc0ad51ef91e6d/README.md?plain=1#L235

Using the example:
`(let [sql-map {:insert-into [:properties]    
               :values [{:name "John", :surname "Smith", :age 34}    
                        {:name "Andrew", :surname "Cooper", :age 12}    
                        {:name "Jane", :surname "Daniels", :age 56}]}]    
  (sql/format sql-map))`

When I evaluated this expression, it resulted in error:
`; Execution error (AssertionError) at honeysql.format/seq->sql (format.cljc:385).    
; Assert failed: Alias should have two parts[:properties]    
(= 2 (count x))`

Replacing the vector for its content worked for me:
`(let [sql-map {:insert-into :properties    
               :values [{:name "John", :surname "Smith", :age 34}    
                        {:name "Andrew", :surname "Cooper", :age 12}    
                        {:name "Jane", :surname "Daniels", :age 56}]}]    
  (sql/format sql-map))`

Was the error on my side or is the documentation wrong?

**Comment by seancorfield** [comment]
Since that assertion does not exist in HoneySQL 2.0 (indeed, that _file_ `format.cljc` does not exist in 2.0), you must be using 1.0?

The README for 1.0.x can be found here: https://github.com/seancorfield/honeysql/tree/v1 and it links to the 1.0.x docs on cljdoc.org -- it's entirely possible there are bugs in the 1.0.x docs since it wasn't automatically checked (all the examples in the 2.0.x docs are automatically checked against the 2.0.x code, using the excellent `test-doc-blocks`).
