### ISSUE TITLE
Add a version of `format-expr` that supports options like `:dialect`

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#456]
In Honey SQL 1,  `honeysql.core/format` worked with either arbitrary expressions or with query maps:

```clj
(honeysql.core/format (honeysql.core/call :+ 1 2))
=>
["(1 + 2)"]
```

However with Honey SQL 2, the equivalent function, `honey.sql/format`, only supports maps. There is `honey.sql/format-expr`, but it doesn't accept options like `:dialect` or` :quoted` that you can pass to `honey.sql/format`. 

Use case:

At Metabase we have hundreds of tests like this 

https://github.com/metabase/metabase/blob/c659e767d1371db8820dc867f3538edcd694265a/test/metabase/util/honey_sql_1_extensions_test.clj#L59-L67

using Honey SQL 1. I'm slowly porting everything over to Honey SQL 2 and this is something that has been causing pain in the porting process

**Comment by seancorfield** [comment]
Looking at the code, `format-expr` already takes _some_ options but doesn't process them like `format` does. The latter delegates to `format-dsl` after setting up the `binding` environment.

Given all that, I think the solution is to modify `format` so that it calls `format-dsl` (as now) if passed a hash map but calls `format-expr` otherwise. I believe this will restore the 1.x behavior without breaking anything -- and will be useful for folks who want to format just a SQL expression and then drop it into some other SQL string they already have.

**Comment by seancorfield** [comment]
Can you try the latest version via a git dep and if that works for you, I'll cut a new release.

**Comment by camsaul** [comment]
Yup, looks good to me. Thanks!

**Comment by seancorfield** [comment]
v2.4.972 is up on Clojars.
