### ISSUE TITLE
Consider supporting variadic `:/` and other binary operators

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#459]
A difference I noticed between HoneySQL 1 and Honey SQL 2 is that the format accepts > 2 args for predicates like :/ , while the latter explicitly disallows it...

```clj
(honeysql.core/format {:select [[(honeysql.core/call :/ 1 2 3) :x]]})
;; => ["SELECT (1 / 2 / 3) AS x"]

(honey.sql/format {:select [[[:/ 1 2 3] :x]]})
;; => only binary :/ is supported
```

Should Honey SQL 2 support this? It works in Clojure:

```clj
(/ 1 2 3) => 1/6 ; the same as (/ (/ 1 2) 3)
```

If not, should this be added to the "Differences from 1.x" dox?

**Comment by seancorfield** [comment]
My preference here is to default operators to variadic and switch the internal machinery to use `op-binary` for the few that really need to be binary (`:=` and `:<>` since those have special handling for `nil`).

That would leave `:variadic` in `register-op!` but invert what it does internally.

**Comment by seancorfield** [comment]
Digging into this, I realize that 2.x doesn't support unary operators unless you declare them variadic: it's view of "not variadic" is "strictly binary" -- which the docs do actually call out but really isn't very useful.

I think I'm going to tackle this in two phases:
1. I'm going to make all operators variadic by default, except `:=` and `:<>` (due to the special handling of `nil`), and remove the `:variadic` flag from `register-op!`,
2. I'm going to create a new issue to think about whether arity checking would be useful for operators (and, if so, you could optionally specify an arity when you register new operators and HoneySQL would check that for you).
