### ISSUE TITLE
Support H2's `TRUNCATE TABLE` syntax

### ISSUE THREAD

**Issue by janusvm** [jkk/honeysql#484]
This is a very, very minor thing that only affects the formatting of generated SQL, but I thought I'd just mention it:

It seems that in H2 SQL, the "TABLE" part of `TRUNCATE TABLE tablename ...` is _not_ optional, so in order to express this in HoneySQL, you have to include the keyword `:table` in the sequence of options, and this means it gets formatted as if "table" is the tablename and "tablename" is a keyword.

Example:

```clojure
(sql/format {:truncate [:table :tablename :restart :identity]}) 
; => ["TRUNCATE table TABLENAME RESTART IDENTITY"]
```

It obviously still works just fine with JDBC, but it would probably be nice to have a `:truncate-table` option for clarity — I'm still fairly new to Clojure, and it tripped me up a little to use `{:truncate :tablename}` from the README example and then get a JDBC error back 😅

**Comment by seancorfield** [comment]
Based on my initial research today, it seems that `TABLE` can only be omitted for PostgreSQL and all other databases (that support this non-ANSI extension) seem to require `TABLE`. Since PostgreSQL allows `TABLE` to be specified, I'm going to update `:truncate` to generate `TRUNCATE TABLE` for all dialects.
