### ISSUE TITLE
Support `OVERRIDING SYSTEM VALUE` for inserts

### ISSUE THREAD

**Issue by gpind** [jkk/honeysql#496]
I'm fairly sure the following is standard SQL, but I don't have access to the spec so can't verify. It works in at least [Postgres](https://www.postgresql.org/docs/current/sql-insert.html), though.

When a column is defined with `GENERATED ALWAYS`, like this:
```sql
CREATE TABLE foo (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY)
```
...then you aren't allowed to set that value yourself via `INSERT` unless you specify `OVERRIDING SYSTEM VALUE`:
```sql
INSERT INTO foo (id) OVERRIDING SYSTEM VALUE VALUES (1)
```

AFAICT, it's not possible to add support via `register-clause!`, because we'd need to insert something between the two parts of a `:values` clause. E.g.:
```clj
(sql/register-clause! :overriding-system-value
                      (fn [_ _] ["OVERRIDING SYSTEM VALUE"])
                      :values)
(sql/format {:insert-into :foo :values [{:id 1}] :overriding-system-value true})
; => ["INSERT INTO foo OVERRIDING SYSTEM VALUE (id) VALUES (?)" 1]
;                      ^ clause is in the wrong place
```
The column list would need to be part of `:insert-into` rather than `:values` for that to be possible, but obviously that's not a feasible change. A variant of `:values` could work (`:values-overriding-system-value` maybe), but... 🤮.

What about this?
```clj
{:insert-into :foo
 :values [{:id 1
           ::sql/overriding-system-value true}]}
```

**Comment by gpind** [comment]
Oh, there's also `OVERRIDING USER VALUE` which makes the generated value "win".

**Comment by seancorfield** [comment]
You can make your case work by using `:columns` to specify the column names and then using the form of `:values` that has sequences of sequences (sequences of column values).

If you don't use `:columns`, and rely on the sequences of hash maps form of `:values` then the column names are produced _as part of the formatting of `:values` separately_, independent of `:insert-into`.

You're not the first person to run into this, nor the last -- and I've just updated the docs to make this clearer for the next release.

I'm leaving this open because I'm still thinking about ways to make this work conveniently -- the `overriding` part should clearly be associated with `:insert-into` and that doesn't fit well into how either `:columns` or `:values` work right now... There needs to be more dynamic behavior in the formatter, but I am somewhat loathed to introduce more `binding` stuff...

**Comment by gpind** [comment]
Thanks for the response. Although it's not how we'd prefer to write inserts, the approach you described should work for us.

Probably crazy, but what about hiccup-style props?

```clojure
{:insert-into [{:overriding-value :system}
               :my-table]
 :values ...}
```

**Comment by seancorfield** [comment]
That won't work in the `:columns` case because `:insert-into` is formatted first, then `:columns` (then `:values`).

**Comment by seancorfield** [comment]
Now that I've fixed #501 your prefix options suggestion will work and I've implemented that on the *develop* branch. You can test it by using git deps or the 2.4.9999-SNAPSHOT that will be up on Clojars in a few minutes.

**Comment by seancorfield** [comment]
Docs added for this in the Clause Reference.

**Comment by gpind** [comment]
Awesome, thank you!
