### ISSUE TITLE
register-clause! does not respect :values as argument for before 

### ISSUE THREAD

**Issue by vincent-dm** [jkk/honeysql#500]
Microsoft SQL Server has an [`OUTPUT`](https://learn.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver16) clause, similar to `RETURNING` in PostgreSQL.

The `OUTPUT` clause needs to be placed between the `INSERT INTO` and `VALUES` clauses, but when trying to extend HoneySQL for this, I run into what seems to be a bug:

# Reproducing
## Steps
* Start a REPL with HoneySQL loaded, e.g. `clj -Sdeps '{:deps {com.github.seancorfield/honeysql {:mvn/version "2.4.1045"}}}'`
* Execute the following code:
  ```clj
  (require '[honey.sql :as sql])
  (sql/register-clause! :output :select :values)
  (sql/format {:insert-into :foo :output [:inserted.*] :values [{:bar 1}]})
  ```

## Expected
The new clause is placed after the `INSERT INTO` clause and before the `VALUES` clause:

`["INSERT INTO foo (bar) OUTPUT inserted.* VALUES (?)" 1]`

## Actual
The new clause is placed within the `INSERT INTO` clause, between the table name and the list of column names.

`["INSERT INTO foo OUTPUT inserted.* (bar) VALUES (?)" 1]`

This is invalid syntax for Microsoft SQL Server, leading to `com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'bar'.`.

**Comment by vincent-dm** [comment]
It seems caused by `honey.sql/format-values` which is responsible for formatting the `VALUES` clause but prepends its output with the list of columns under the (wrong) assumption that the preceding clause will always be `INSERT INTO`.

I'm not familiar enough with the inner workings of HoneySQL to figure out how to fix this. I hope it's possible!

**Comment by seancorfield** [comment]
There are several ways to use `:insert-into` and `:values` -- see https://cljdoc.org/d/com.github.seancorfield/honeysql/2.4.1045/doc/getting-started/sql-clause-reference#insert-into-replace-into

You'll need to use `{:insert-into :foo :columns [:bar] :output [:inserted.*] :values [[1]]}` which produces:

```clojure
user=>  (sql/format {:insert-into :foo :columns [:bar] :output [:inserted.*] :values [[1]]})
["INSERT INTO foo (bar) OUTPUT inserted.* VALUES (?)" 1]
```

**Comment by vincent-dm** [comment]
Hi Sean,

Thanks for the quick response!

Your suggestion would indeed work, but I would consider it a workaround. After all, the docstring of `register-clause!` promises that _"it is inserted immediately prior to that clause [specified by `before`]"_.

I understand that this is not easy to fix due to the implementation of `honey.sql/format-values`, but maybe the docstring of `register-clause!` can be enhanced to clarify that it doesn't always support `:values` as a `before` param?

**Comment by seancorfield** [comment]
Clauses are evaluated (formatted) in strict precedence order which produces right-to-left elements of the SQL string.

`register-clause!` "supports" `:values` as a `before` param just fine. Your `:output` clause is formatted **BEFORE** the `:values` clause is formatted.

The section of the docs I linked you to explicitly calls out the formatting of `:values` (it's called out in the CTE section near the top too).

I will add a note to the **values** docs https://cljdoc.org/d/com.github.seancorfield/honeysql/2.4.1045/doc/getting-started/sql-clause-reference#values to clarify that `:values` with a sequence of hash maps produces `(cols) VALUES (values)` (which is why several sections call out that you need to use the sequence of sequences when something else identified the column names).

**Comment by seancorfield** [comment]
See https://github.com/seancorfield/honeysql/commit/ba336f2884cbcac4025370bd0687fdc21da269ff#diff-49952233047493b6ede50abf2fce16b71d9c717d3b7c050f64e86a4514a1db1bL1040 for the doc changes I made.

**Comment by vincent-dm** [comment]
Yes, that clarifies that the behavior is intended. Thank you!
