### ISSUE TITLE
`:union` and similar ops should format their arguments wrapped in parentheses

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#516]
```clj
(sql/format {:union [{:with   [[:x {:select [[[:inline 1]]]}]]
                      :select :*
                      :from   :x}
                     {:with   [[:y {:select [[[:inline 2]]]}]]
                      :select :*
                      :from   :y}]})
=> ["WITH x AS (SELECT 1) SELECT * FROM x UNION WITH y AS (SELECT 2) SELECT * FROM y"]
```

It's considered an invalid query by at least PostgreSQL:
```
[42601] ERROR: syntax error at or near "WITH"
Position: 44
```

But this works just fine:
```sql
(WITH x AS (SELECT 1) SELECT * FROM x)
UNION
(WITH y AS (SELECT 2) SELECT * FROM y)
```

**Comment by p-himik** [comment]
Working on a PR.

**Comment by p-himik** [comment]
Oh, I see that there's #451 and seems like the proposed solution is to just use `:nest`.

However, why not add parentheses by default?

**Comment by seancorfield** [comment]
Because not all databases accept `( .. ) UNION ( .. )` which is why that was removed.

**Comment by p-himik** [comment]
Ah, sorry, didn't notice the mention of that at first.

In that case, would it make sense to make this kind of automatic parentheses wrapping a part of the dialects? It seems not that dissimilar to quoting.

Not sure how useful this information is, but I just tested a bunch of databases at http://sqlfiddle.com/, https://www.db-fiddle.com/, https://sqlite.org/fiddle/.
Seems that MySQL 5.* does not support (... UNION ...), but it does support `(...) UNION (...)` just fine. MySQL  8.0 supports both separately and in combination.
The only database among the ones available at those websites that doesn't support `(...) UNION (...)` is SQLite.
The databases that `next-jdbc` uses for tests (except for MySQL and MS SQL since I don't have those locally) all support `(...) UNION (...)`, except for SQLite and Derby.

**Comment by seancorfield** [comment]
At this point, changing the behavior is going to break someone's code. `:nest` allows you to explicitly add parens _if needed_ but you have no way to _unnest_ parens if you end up in a situation where you can't have them or just don't want them. See #107 which was what prompted the _original_ change and then #279 prompted the addition of `:nest`.

This typically only matters for more complex statements where you're also limiting or ordering etc over the result of the `union` (rather than within any subquery).
